[workspace]
resolver = "2"
members = [
  "crates/risk-core",
  "crates/risk-server-tokio",
  "crates/risk-bench",
  "crates/risk-bench2",
  "crates/risk-server-glommio"

]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
